### ISSUE TITLE
100 % CPU utilization when Mooltipass device plugged in

### ISSUE THREAD

**Issue by matthias-g** [mooltipass/moolticute#594] opened 2020-01-24 08:28 UTC
### Expected behavior
`moolticuted` uses below 100 % CPU resources.

### Actual behavior
Since a couple of days, `moolticuted` has a CPU utilization of 100 % on my system (Arch Linux, installed from [AUR](https://aur.archlinux.org/packages/moolticute/)) when the device is plugged in. It doesn't make a difference whether the card has been unlocked. Despite the high CPU utilization, everything else seems to be working fine.

### Steps to reproduce
Unfortunately, I don't have another installation of Arch Linux to test whether this happens generally.
I've tried reinstalling Moolticute, deleting `~/config/mooltipass` and `~/.local/share/mooltipass`, resetting the device, and using another device.

Starting `moolticuted` from the command line and then plugging in the device, shows the following message repeatedly:
`DEBUG: :0 - "MOOLTIPASS_STATUS (0x00b9)"  received, resending command  "END_MEMORYMGMT (0x00d3)"`
However, this stops after unlocking the device, while the CPU utilization is still at 100 %.

### Moolticute Version
v0.42.1

### Operating System
Arch Linux

### Mooltipass Device
Same for Mooltipass Standard and Mooltipass Mini

**Comment by Tiki-God** [comment] 2020-02-04 10:43
I also seem to be affected by this on one of my systems, but not on another.  Both use moolticute built from Git.

Desktop running moolticute 0.42.26 and 0.42.27 runs at 100% of a single CPU core when the minBLE is plugged in.  Laptop running 0.42.25 isn't affected.  Downgraded the desktop to 0.42.25 and the issue persists.  Upgraded laptop to 0.42.27 and there's no problem.

So it doesn't seem Moolticute version related based on my quick tests.

**Comment by Tiki-God** [comment] 2020-02-04 11:14
Further tested replicated the symptoms on my laptop.  Upgraded laptop kernel from 5.4.6 to 5.5.1 (to be more inline with the desktop) and the CPU usage jumped.

On the desktop I downgraded the kernel from 5.5.0 to 5.4.13 and the problem persisted.  Downgraded from 5.4.13 to 5.4.5 and I'm back to normal CPU usage.

Might be worth someone else verifying that the kernel version change is consistent on other systems.

**Comment by byterazor** [comment] 2020-02-08 18:29
I can confirm that after a kernel change from 5.3.* to 5.4.* moolticuted uses 100% cpu time!

**Comment by limpkin** [comment] 2020-02-08 19:30
thanks for your debugging everyone!
@deXol : urgent task for you :)

**Comment by r-cheologist** [comment] 2020-02-14 07:37
I'm seeing the same on Arch using the appimage from the homepage and kernel 
Linux KI-P0695 5.5.3-arch1-1 #1 SMP PREEMPT Tue, 11 Feb 2020 15:35:41 +0000 x86_64 GNU/Linux

**Comment by byterazor** [comment] 2020-02-20 21:11
Hey, will this Issue be solved soon ? It's unusable on my laptop because 100% CPU usage means the fan is constantly working and battery time is low.... And to use all my laptops features I am required to run a current kernel....

**Comment by Arffeh** [comment] 2020-02-21 05:02
Agreed.

I've had to cease beta testing entirely due to this.

**Comment by bitgestalt** [comment] 2020-02-22 13:58
I think the cause of the problem is that MPDevice_linux [creates](https://github.com/mooltipass/moolticute/blob/master/src/MPDevice_linux.cpp#L56) a QSocketNotifier waiting for the device file descriptor to become writable, but doesn't handle its activated() signal. This appears to create a busy loop in the Qt event handler.

Removing sockNotifWrite (which is unused anyway) makes the CPU utilization drop back to normal levels (Tested on Fedora with kernel 5.4.20).  I won't create a PR yet, though, because I think it should be investigated what the supposed purpose of sockNotifWrite was.

On a side note, QSocketNotifier is enabled by default, so the explicit calls to setEnabled(true) in MPDevice_linux and UsbMonitor_linux aren't neccessary.

**Comment by frankenstein91** [comment] 2020-02-23 16:54
same problem on my system :(

**Comment by limpkin** [comment] 2020-02-23 20:44
Hello all,
We expect to push an update this week that solves this :)

**Comment by limpkin** [comment] 2020-03-01 14:40
Hello All,
Could you compile from source and confirm this is now fixed? 
The arch package should hopefully be released next week.

**Comment by Tiki-God** [comment] 2020-03-02 08:09
Just compiled it this morning and it seems like the issue is resolved as I'm no longer seeing the high CPU usage.

**Comment by Trim** [comment] 2020-03-02 08:47
> Just compiled it this morning and it seems like the issue is resolved as I'm no longer seeing the high CPU usage.

Same here. I've tried on two computers, it worked well on both :+1: 

(Debian Bullseye amd64)

**Comment by limpkin** [comment] 2020-03-03 15:40
awesome!!!

**Closed by limpkin** 2020-03-03 15:40 UTC

**Comment by r-cheologist** [comment] 2020-04-01 15:37
Just pulled this in from AUR - and after `systemctl restart moolticuted.service`: silent bliss! Thanks!

**Comment by frankenstein91** [comment] 2020-04-04 14:36
works for me too.
Thank you
