### ISSUE TITLE
_unlock_ service locks itself again after second unlock

### ISSUE THREAD

**Issue by rms5566** [mooltipass/moolticute#680] opened 2020-06-04 13:10 UTC
### Expected behavior
If you use the unlock Service it should not lock the Mooltipass again
### Actual behavior
If you use the unlock Service the Mooltipass locks itself every second try.
### Step by step guide to reproduce the problem
1) insert smartcard and pin
2) enable _unlock_ service with two accounts
3) set the unlock feature to Enter + Pass / WIN + L
4) unplug the smartcard
5) windows is locked and Mooltipass as well
6) enter smartcard and pin
7) windows is unlocked but the Mooltipass is locked again
8) The mooltipass goes in sleep mode and wake up again after less then 1 second and it won't stop. 
### Moolticute Version
v0.43.17-testing

### Firmware Version
AUX MCU version:  0.25
Main MCU version:  0.32

### Operating System
- Windows 10 Enterprise 2016 LTSB

**Comment by limpkin** [comment] 2020-06-06 08:24
managed to reproduce it !

@deXol when the lock device is sent and the "please retry" is received, we should just give up :)

**Comment by limpkin** [comment] 2020-10-01 17:49
is this bug still valid?

**Comment by ThunderKing54** [comment] 2020-10-02 08:41
Hello Mathieu, it is still there. The Mooltipass locks itself instantly after uusing the unlock feature the scond time

**Comment by ThunderKing54** [comment] 2020-10-02 08:44
Wait a minute. I have to update Moolticute. I test it again

**Comment by ThunderKing54** [comment] 2020-10-02 08:51
It is still there but this time it locks the Mooltipass right after I insert my pin the second time.

**Comment by limpkin** [comment] 2020-12-14 19:16
@ThunderKing54 what about now? :D

**Comment by ThunderKing54** [comment] 2020-12-16 12:41
Cant reproduce it

**Comment by ThunderKing54** [comment] 2020-12-16 12:42
Nope sorry it still locks itself ^^

**Comment by limpkin** [comment] 2021-09-01 19:49
@ThunderKing54 this should be now fixed, can you confirm? :)

**Closed** 2023-03-12 12:57 UTC
