### ISSUE TITLE
Unable to delete account and rename account at same time

### ISSUE THREAD

**Issue by kbembedded** [mooltipass/moolticute#706] opened 2020-09-02 02:29 UTC
### Expected behavior
In Moolticute management mode, I've got two accounts, "account" and "account - new". I would like to remove "account" and rename "account - new" to be just "account". I used this paradigm when migrating a password for a really sensitive database so that if something happened, everything would revert, and I'd still have old password available.

### Actual behavior
There is an error from Moolticute in the logs. Turns out, Moolticute doesn't really like deleting one index and then renaming another to be the same. See redacted output below:

DEBUG: (2020-09-01T19:21:52.888) :0 - Removing child  "account"  with parent  "[REDACTED]"  from DB
INFO: (2020-09-01T19:21:52.888) :0 - Checking database...
WARNING: (2020-09-01T19:21:52.891) :0 - Orphan child found: "account" at address: "[REDACTED ADDRESS]"
DEBUG: (2020-09-01T19:21:52.891) :0 - Number of parent orphans: 0
DEBUG: (2020-09-01T19:21:52.891) :0 - Number of children orphans: 1
DEBUG: (2020-09-01T19:21:52.891) :0 - Number of data parent orphans: 0
DEBUG: (2020-09-01T19:21:52.891) :0 - Number of data children orphans: 0
INFO: (2020-09-01T19:21:52.891) :0 - Errors were found in the database
CRITICAL: (2020-09-01T19:21:52.891) :0 - Error in our local DB (algo PB?)

I'm not sure if there is anything that can really be done to accommodate this set of steps aside from document around it or maybe find a better way to detect that its happening and give a more useful error.

### Step by step guide to reproduce the problem
With any given parent, create a child of "account" and "account - new". Go in to credential management mode and in one session, remove "account" and rename "account - new" to be "account" Click save all and behold the error.

### Moolticute Version
v0.44.0

### Operating System

- Windows 7/10

### Mooltipass Device
- The Mooltipass Mini

**Comment by kbembedded** [comment] 2020-09-02 02:30
Whoops. Forgot to add a workaround/fix of:

Remove old account, save and exit management mode. Re-enter management mode, and rename the second account to match the first name.

**Comment by limpkin** [comment] 2022-01-29 13:59
duplicate of #917

**Comment by kbembedded** [comment] 2022-01-29 18:25
I'd argue that #917 and this are different issues and request they both are left open. Unless there is some slim chance they are related under the hood.

This specifically is in regards to, in the same MMM session, deleting an account "X" and then creating/renaming another account of the same name of "X" fails. I've not tested this bug in recent versions of moolticute and can if wanted.

#917 is that its not possible to delete a login name of a credential that has the login field already populated. Use case where there is not login, just an account and a password, e.g. whole disk encryption where the "site" is just the disk name, no login, and a password. If you create a login name, you can't later delete the name.

**Comment by limpkin** [comment] 2022-01-29 21:15
my sincere apologies, you're indeed right!

**Closed** 2022-03-04 21:36 UTC
Labels: bug
