### ISSUE TITLE
Window auto resize disappear on macOS

### ISSUE THREAD

**Issue by GuillaumeHemmen** [mooltipass/moolticute#1017] opened 2022-03-26 11:41 UTC
### Expected behavior
The window should not disappear.

### Actual behavior
The window disappear when we double click on the top bar with "Moolticute" written.

The only way to get the window back it to exit Moolticute via the widget.

https://user-images.githubusercontent.com/6839630/160237760-9c9742d4-9012-4554-999c-b452aefde6ec.mp4

### Step by step guide to reproduce the problem
- launch the app.
- Double click on the title bar.
- You see the window resizing smaller and smaller until it disappear.

### Operating System
- MacOS  
  

### Mooltipass Extension
N/A

### Mooltipass Device
N/A

**Comment by limpkin** [comment] 2022-06-18 09:37
Hello there! 
We've just released our latest moolticute beta for macOS, compiled with the QT6 framework (it took us a while...). Would you be able to download and install it at https://betas.themooltipass.com/v0.55.10-testing/Moolticute-v0.55.10-testing.dmg and let us know if you still experience this issue?

**Comment by limpkin** [comment] 2023-03-12 10:26
duplicate of https://github.com/mooltipass/moolticute/issues/1133

**Closed by limpkin** 2023-03-12 10:26 UTC
Labels: to tackle after qt6 migration
