### ISSUE TITLE
Moolitcute crashes on device disconnect

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/moolticute#613] opened 2020-03-02 09:23 UTC
### Expected behavior
If you disconnect your Mooltipass mini BLE the Moolticute Deamon shouldn't crash.
### Actual behavior
If you disconnect your Mooltipass mini BLE multiple times it crashes the Moolticute Deamon.
```
INFO: (2020-03-02T10:15:42.068) :0 - "Waiting job"
DEBUG: (2020-03-02T10:15:42.368) :0 - Resetting flip bit for BLE
INFO: (2020-03-02T10:15:42.511) :0 - "Get PlatInfo"
DEBUG: (2020-03-02T10:15:42.511) :0 - Platform send command:  "GET_PLAT_INFO (0x0003)"
DEBUG: (2020-03-02T10:15:42.512) :0 - Full packet# 0 :  "[0x04, 0x00, 0x03, 0x00, 0x00, 0x00]"
DEBUG: (2020-03-02T10:15:42.514) :0 - "PLEASE_RETRY (0x0002)"  received, resending command  "GET_PLAT_INFO (0x0003)"
DEBUG: (2020-03-02T10:15:42.821) :0 - Platform send command:  "GET_PLAT_INFO (0x0003)"
DEBUG: (2020-03-02T10:15:42.821) :0 - Full packet# 0 :  "[0x84, 0x00, 0x03, 0x00, 0x00, 0x00]"
DEBUG: (2020-03-02T10:15:42.825) :0 - "PLEASE_RETRY (0x0002)"  received, resending command  "GET_PLAT_INFO (0x0003)"
WARNING: (2020-03-02T10:15:43.022) :0 - Failed to read data from device!
WARNING: (2020-03-02T10:15:43.022) :0 - "Das Gerät ist nicht angeschlossen."
DEBUG: (2020-03-02T10:15:43.036) :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_1209&PID_4321&MI_00#7&279be68d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-03-02T10:15:43.036) :0 - Disconnecting:  "\\\\?\\hid#vid_1209&pid_4321&mi_00#7&279be68d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-03-02T10:15:43.036) :0 - Mooltipass disconnected
DEBUG: (2020-03-02T10:15:43.037) :0 - List usb devices...
DEBUG: (2020-03-02T10:15:43.039) :0 - Disconnecting devices
DEBUG: (2020-03-02T10:15:43.039) :0 - Device removed:  "{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  -  "\\\\?\\HID#VID_1209&PID_4321&MI_01#7&3c4a8cb&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"
DEBUG: (2020-03-02T10:15:43.039) :0 - "\\\\?\\hid#vid_1209&pid_4321&mi_01#7&3c4a8cb&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}"  is not connected.
DEBUG: (2020-03-02T10:15:43.039) :0 - List usb devices...
DEBUG: (2020-03-02T10:15:43.050) :0 - Disconnecting devices
DEBUG: (2020-03-02T10:15:43.050) :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_1209&PID_4321&MI_01#7&3c4a8cb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-03-02T10:15:43.051) :0 - "\\\\?\\hid#vid_1209&pid_4321&mi_01#7&3c4a8cb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"  is not connected.
DEBUG: (2020-03-02T10:15:43.051) :0 - List usb devices...
DEBUG: (2020-03-02T10:15:43.056) :0 - Disconnecting devices
DEBUG: (2020-03-02T10:15:43.056) :0 - Device removed:  "{4d1e55b2-f16f-11cf-88cb-001111000030}"  -  "\\\\?\\HID#VID_1209&PID_4321&MI_02#7&201294f7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
DEBUG: (2020-03-02T10:15:43.056) :0 - "\\\\?\\hid#vid_1209&pid_4321&mi_02#7&201294f7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"  is not connected.
DEBUG: (2020-03-02T10:15:43.056) :0 - List usb devices...
DEBUG: (2020-03-02T10:15:43.061) :0 - Disconnecting devices
DEBUG: (2020-03-02T10:15:43.061) :0 - Device removed:  "{a5dcbf10-6530-11d2-901f-00c04fb951ed}"  -  "\\\\?\\USB#VID_1209&PID_4321#5&29c58453&0&4#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"
DEBUG: (2020-03-02T10:15:43.061) :0 - "\\\\?\\usb#vid_1209&pid_4321#5&29c58453&0&4#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"  is not connected.
DEBUG: (2020-03-02T10:15:43.061) :0 - List usb devices...
DEBUG: (2020-03-02T10:15:43.064) :0 - Disconnecting devices
WARNING: (2020-03-02T10:16:55.205) :0 - Daemon exits with error code  -1073741819  Exit Status :  QProcess::ExitStatus(CrashExit
```
### Step by step guide to reproduce the problem
1) insert the smartcard into the moolitpass and enter your pin
2) disconnect your mooltipass and connect it multiple times.
3) the moolticute deamon crashes.

### Moolticute Version
v0.42.40-testing

### Operating System
- Windows 10 Enterprise LTSB 2016

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by limpkin** [comment] 2020-03-02 12:40
duplicate of #600

**Closed by limpkin** 2020-03-02 12:40 UTC
