### ISSUE TITLE
Multicute appimage is not prepared for wayland

### ISSUE THREAD

**Issue by d4g** [mooltipass/moolticute#853] opened 2021-06-16 16:05 UTC
### Missing feature
When running the multicute appimage on wayland, it does not launch throwing the following error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

This is because of the following environment variable:
```
QT_QPA_PLATFORM=wayland
```

### Justification
Wayland is the future. Xorg is the past. Support for wayland is mandatory ;)

### Workarounds
Use Xwayland by exporting the following environment variable before launch:
```
export QT_QPA_PLATFORM=
```

**Comment by limpkin** [comment] 2021-07-08 08:05
duplicate of #872

**Comment by limpkin** [comment] 2021-07-08 08:47
from @raoulh : it seems we need to package qt_wayland and upgrade our qt

**Comment by limpkin** [comment] 2021-08-30 17:30
duplicate of #872

**Closed by limpkin** 2021-08-30 17:30 UTC
Labels: bug
