### ISSUE TITLE
Can't access any tab after entered Database File Management mode

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/moolticute#657] opened 2020-04-30 11:12 UTC
### Expected behavior
If you enter the Database File Management Mode and press STRG + ALT + F3 all tabs should be enabled again.
### Actual behavior
If you enter the Database File Management Mode and press STRG + ALT + F3 all tabs are still disabled and you can't escape the BLE Developer Tab
### Step by step guide to reproduce the problem
1) open moolticute and go the the Files Tab
2) Press the Button "Enter Database File Management"
3) accept the prompt on your Mooltipass
4) Press STRG + ALT + F3 to enter the BLE Developer Tab
5) Now you're stuck inside this Tab
### Moolticute Version
v0.43.14-testing
### Operating System
Mention if you are using either:
- Windows 10 Pro

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by ubergeek77** [comment] 2022-02-05 23:11
@limpkin I was going to file a new issue, but this one from ~2 years ago accurately describes my problem.

This happened to me today on the latest version of Moolticute (0.53.7). Strangely, completely uninstalling Moolticute, rebooting the computer, removing the device from the computer, etc, does not solve the problem. I am completely unable to use Moolticute; no tabs can be interacted with.

Is there a registry key, or cache file somewhere, that is keeping the tab state? Anything that might persist across reboots or reinstalls? That's the only way I can think of that this might happen.

**Comment by limpkin** [comment] 2022-02-05 23:15
can you confirm the developer tab stay enabled across moolticute restarts? that's extremely odd..

**Comment by ubergeek77** [comment] 2022-02-06 01:10
I can open the developer tab with CTRL +SHIFT + F3, and it will navigate to that tab for me, but I can't click off of that tab while it is open.

Additionally, with the developer tab enabled, if I close Moolticute from the tray (Right click > Quit), then start it again, the developer tab does NOT stay enabled.

**Comment by limpkin** [comment] 2022-02-06 08:56
the latter is expected behavior, the former not. on which version of moolticute is this happening?

**Comment by ubergeek77** [comment] 2022-02-09 00:24
> the latter is expected behavior, the former not. on which version of moolticute is this happening?

@limpkin Apologies, missed the notification on this one.

This is on 0.53.7. I also tried 0.53.2 (the next-latest stable version) with the same results. And considering the installer uninstalls Moolticute when up/downgrading, and I uninstalled Moolticute manually, surely there must be some leftover file/registry value? Either that, or some kind of bug or incompatibility with my system. I honestly can't explain this. I can't reproduce it on any other machine, either.

If it helps, this is a rather high DPI screen (3840x2400) with higher display scaling (350%). And there are other issues with Moolticute at this level of scaling (window size issue with buttons being cut off), but I'll save that for another issue as I don't think they are related.

Let me know if I can collect any other information, and I'll do my best.

**Comment by limpkin** [comment] 2022-02-09 09:14
@ubergeek77 is it possible you have the tutorial displayed at the bottom of the window?

**Comment by ubergeek77** [comment] 2022-02-10 22:50
> @ubergeek77 is it possible you have the tutorial displayed at the bottom of the window?

@limpkin 

Ah, you are entirely correct!

I had completely forgotten there was even a tutorial. I'm not sure what made it appear during an active install.

I suppose this leads me into the next issue then - I didn't know the tutorial was active, because the window is far too large to see the tutorial. The bottom of Moolticute gets cut off on this level of display scaling:

![moolticute](https://user-images.githubusercontent.com/3455585/153509329-8f36502a-cf97-4df7-87ea-886f1d4b71da.png)

I realize that a display scaling of 350% is very non-standard, but this is actually the computer of an older relative, and the scaling needs to be this high for visual accessibility. The screen is 4K by pixel count, but *physically* small, so display scaling is the only way to get text large enough for this individual to read.

For other applications, this isn't a problem at all. However, Moolticute currently has a fixed window size, and resizing the window is prohibited. If this were any other application, I would simply resize the window to fit the screen constraints. Unfortunately, I can't do this in Moolticute.

If you like, I can file an issue about this specifically. Just let me know what other info you would like me to provide in that case.

Thanks for the help!

**Comment by ubergeek77** [comment] 2022-02-10 23:26
> is this even with the latest testing build, in which we put lots of effort to reduce its Y dimension? :)

Sadly not :(

I've just upgraded this machine to use `v0.53.13-testing`. I can see the red bar at the bottom now, but I still cannot interact with the buttons down that low:

![testing](https://user-images.githubusercontent.com/3455585/153513898-bc8bb6f5-1903-4fe9-9ee3-2e7728f0346d.png)

**Comment by limpkin** [comment] 2022-02-11 08:29
that's quite some scaling you got there :)

@dexol is it possible to detect when the tutorial is out of screen boundaries?

**Comment by limpkin** [comment] 2022-02-11 20:06
As it's effectively a duplicate of https://github.com/mooltipass/moolticute/issues/961 i'll therefore close this one

**Closed by limpkin** 2022-02-11 20:06 UTC
Labels: bug

**Comment by limpkin** [comment] 2022-02-12 08:08
that's a very good point. thanks for your help @ubergeek77  :)
