### ISSUE TITLE
Moolticute window disappears on resize

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/moolticute#1012] opened 2022-03-17 18:50 UTC
### Behavior
When resizing the application windows on macOS the window flickers and ocasionally disappears

### Moolticute Version
0.54.1 testing
### Operating System
- MacOS 12.3
  
![ezgif-4-57eb7ebfd4](https://user-images.githubusercontent.com/16672190/158874100-d08e3307-442b-4be9-998c-4a5e6f93604c.gif)

**Comment by limpkin** [comment] 2022-06-18 09:38
Hello there! 
We've just released our latest moolticute beta for macOS, compiled with the QT6 framework (it took us a while...). Would you be able to download and install it at https://betas.themooltipass.com/v0.55.10-testing/Moolticute-v0.55.10-testing.dmg and let us know if you still experience this issue?

**Comment by WebmasterTD** [comment] 2022-07-01 14:16
I just tested it with version 55.12-testing and it's still happening.

**Comment by limpkin** [comment] 2023-03-12 10:28
duplicate of https://github.com/mooltipass/moolticute/issues/1133

**Closed by limpkin** 2023-03-12 10:28 UTC
Labels: to tackle after qt6 migration
